spring:
  datasource:
    url: jdbc:h2:file:~/db/shopping
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: db/migration
    url: $spring.datasource.url

viniciusit:
  swagger:
    devUrl: "http://localhost:8080"
    prodUrl: "http://localhost:8080"
  serviceUser: "it.svc.shopping"

